POST http://localhost:8080/consultas
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJleHAiOjE2OTg5MzI3MTR9.uJXyPL-qoUQTlb-q6cN13qu9Uemfgi6i3pdhBXeI_WQ

{
  "idPaciente": "5",
  "idMedico": "4",
  "data": "2023-11-03T09:16"
}

### POST cadastrar consultas
POST http://localhost:8080/consultas
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJleHAiOjE2OTg5MzI3MTR9.uJXyPL-qoUQTlb-q6cN13qu9Uemfgi6i3pdhBXeI_WQ

{
"idPaciente": "3",
"idMedico": "4",
"data": "2023-11-20T10:00"
}

### GET consulta
GET http://localhost:8080/consultas
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmEuc291emFAdm9sbC5tZWQiLCJpc3MiOiJBUEkgVm9sbC5tZWQiLCJleHAiOjE2OTg5MzI3MTR9.uJXyPL-qoUQTlb-q6cN13qu9Uemfgi6i3pdhBXeI_WQ

